# Generated by Django 3.2 on 2022-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['leave', 'name'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created',
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated',
        ),
        migrations.AddField(
            model_name='page',
            name='dni',
            field=models.CharField(default='', max_length=200, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='page',
            name='entry',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='page',
            name='leave',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de egreso'),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre y apellido'),
        ),
        migrations.AddField(
            model_name='page',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio por habitación'),
        ),
        migrations.AddField(
            model_name='page',
            name='reserve',
            field=models.IntegerField(default=0, verbose_name='Monto abonado'),
        ),
        migrations.AddField(
            model_name='page',
            name='room',
            field=models.SmallIntegerField(default=0, verbose_name='Habitación'),
        ),
    ]
