# Generated by Django 3.2 on 2022-12-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20221108_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='page',
            name='price',
        ),
        migrations.AddField(
            model_name='page',
            name='age',
            field=models.CharField(default='', max_length=200, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='page',
            name='diagnostic',
            field=models.CharField(default='', max_length=200, verbose_name='Diagnostico principal'),
        ),
        migrations.AddField(
            model_name='page',
            name='height',
            field=models.SmallIntegerField(default=0, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='page',
            name='medication',
            field=models.CharField(default='', max_length=200, verbose_name='Medicación administrada'),
        ),
        migrations.AddField(
            model_name='page',
            name='weight',
            field=models.SmallIntegerField(default=0, verbose_name='Peso'),
        ),
    ]
