# Generated by Django 3.2 on 2022-12-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20221214_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='reserve',
        ),
        migrations.AlterField(
            model_name='page',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='page',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'),
        ),
    ]
