# Generated by Django 3.2 on 2022-12-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20221214_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observación'),
        ),
    ]
