# Generated by Django 3.2 on 2022-12-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizacion'),
        ),
    ]
